# Generated by Django 5.2.17 on 2026-09-24 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_name', models.CharField(max_length=100)),
                ('prompt_version', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=255)),
                ('backend', models.CharField(choices=[('mock', 'Mock'), ('bedrock', 'Bedrock')], max_length=10)),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('cost_estimate_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('ok', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stories.story')),
            ],
        ),
    ]
