# Generated by Django 5.2.17 on 2026-10-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmcall',
            name='backend',
            field=models.CharField(choices=[('mock', 'Mock'), ('bedrock', 'Bedrock'), ('strands', 'Bedrock via Strands')], max_length=10),
        ),
    ]
