# Generated by Django 5.2.17 on 2026-09-24 13:51

import apps.core.ids
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proverb',
            fields=[
                ('id', models.CharField(default=apps.core.ids.proverb_id, editable=False, max_length=15, primary_key=True, serialize=False)),
                ('original_text', models.TextField()),
                ('language', models.CharField(max_length=100)),
                ('spoken_form', models.TextField()),
                ('translation', models.TextField(blank=True)),
                ('meaning_note', models.TextField()),
                ('speak_original_ok', models.BooleanField(default=False)),
                ('culture', models.CharField(max_length=120)),
                ('region', models.CharField(max_length=100)),
                ('source_citation', models.TextField()),
                ('second_source_citation', models.TextField(blank=True)),
                ('license', models.CharField(max_length=255)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('single_source', 'Single source'), ('verified', 'Verified'), ('disputed', 'Disputed')], max_length=16)),
                ('dispute_note', models.TextField(blank=True)),
                ('themes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), blank=True, default=list, size=None)),
                ('tone_ok', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('verification_status', 'verified'), _negated=True), models.Q(('source_citation__gt', ''), ('second_source_citation__gt', '')), _connector='OR'), name='verified_proverb_needs_two_citations')],
            },
        ),
    ]
