# Generated by Django 5.2.17 on 2026-09-24 13:51

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('feed_url', models.URLField(unique=True)),
                ('region', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=16)),
                ('terms_url', models.URLField()),
                ('terms_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('use_policy', models.CharField(choices=[('headline_snippet_only', 'Headline and snippet only'), ('blocked', 'Blocked')], default='blocked', max_length=24)),
                ('attribution_text', models.CharField(blank=True, max_length=300)),
                ('active', models.BooleanField(default=False)),
                ('min_interval_minutes', models.PositiveIntegerField(default=30)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('etag', models.CharField(blank=True, max_length=255)),
                ('last_modified', models.CharField(blank=True, max_length=255)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('circuit_state', models.CharField(choices=[('closed', 'Closed'), ('open', 'Open')], default='closed', max_length=8)),
                ('circuit_opened_reason', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('ok', 'OK'), ('not_modified', 'Not modified'), ('blocked', 'Blocked'), ('rate_limited', 'Rate limited'), ('error', 'Error'), ('skipped_by_policy', 'Skipped by policy')], max_length=20)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fetch_logs', to='news.sourcefeed')),
            ],
            options={
                'ordering': ('-requested_at',),
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_kind', models.CharField(choices=[('news_snippet', 'News snippet'), ('reference', 'Reference'), ('curated', 'Curated')], max_length=16)),
                ('url_clean', models.URLField(max_length=2048)),
                ('url_hash', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('snippet', models.CharField(max_length=300, validators=[django.core.validators.MaxLengthValidator(300)])),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(max_length=16)),
                ('region_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('cluster_key', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='news.sourcefeed')),
            ],
            options={
                'ordering': ('-published_at', '-fetched_at'),
            },
        ),
    ]
