# Generated by Django 5.2.17 on 2026-09-24 13:51

import apps.core.ids
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('news', '0001_initial'),
        ('wisdom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.CharField(default=apps.core.ids.story_id, editable=False, max_length=15, primary_key=True, serialize=False)),
                ('cluster_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('is_synthetic', models.BooleanField(default=False)),
                ('handle', models.CharField(max_length=120)),
                ('tone_class', models.CharField(choices=[('neutral', 'Neutral'), ('sensitive', 'Sensitive')], default='neutral', max_length=12)),
                ('themes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), blank=True, default=list, size=None)),
                ('region', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=12)),
                ('rejection_reasons', models.JSONField(blank=True, default=list)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('pipeline_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='core.pipelinerun')),
            ],
            options={
                'ordering': ('-published_at', '-last_updated_at'),
            },
        ),
        migrations.CreateModel(
            name='StoryTelling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tone', models.CharField(choices=[('light', 'Light'), ('balanced', 'Balanced'), ('serious', 'Serious')], max_length=10)),
                ('closing_kind', models.CharField(choices=[('moral', 'Moral'), ('reflection', 'Reflection'), ('none', 'None')], default='reflection', max_length=10)),
                ('moral', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('checked', 'Checked'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=10)),
                ('is_curated', models.BooleanField(default=False)),
                ('checker_report', models.JSONField(blank=True, default=dict)),
                ('revision_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tellings', to='stories.story')),
            ],
        ),
        migrations.CreateModel(
            name='TellingBeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('text_template', models.TextField()),
                ('telling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beats', to='stories.storytelling')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='TellingProverb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=16)),
                ('role', models.CharField(choices=[('opening', 'Opening'), ('turn', 'Turn'), ('closing', 'Closing')], max_length=10)),
                ('proverb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='telling_links', to='wisdom.proverb')),
                ('telling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proverb_links', to='stories.storytelling')),
            ],
        ),
        migrations.CreateModel(
            name='StoryContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(choices=[('background', 'Background'), ('why_it_matters', 'Why it matters'), ('consequence', 'Consequence')], max_length=16)),
                ('text', models.TextField()),
                ('articles', models.ManyToManyField(related_name='context_items', to='news.article')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_items', to='stories.story')),
            ],
            options={
                'ordering': ('order',),
                'constraints': [models.UniqueConstraint(fields=('story', 'order'), name='unique_context_order')],
            },
        ),
        migrations.CreateModel(
            name='StoryFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('articles', models.ManyToManyField(related_name='facts', to='news.article')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='stories.story')),
            ],
            options={
                'ordering': ('order',),
                'constraints': [models.UniqueConstraint(fields=('story', 'order'), name='unique_fact_order')],
            },
        ),
        migrations.CreateModel(
            name='StoryPerspective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('label', models.CharField(max_length=120)),
                ('summary', models.TextField()),
                ('articles', models.ManyToManyField(related_name='perspectives', to='news.article')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perspectives', to='stories.story')),
            ],
            options={
                'ordering': ('order',),
                'constraints': [models.UniqueConstraint(fields=('story', 'order'), name='unique_perspective_order')],
            },
        ),
        migrations.AddConstraint(
            model_name='storytelling',
            constraint=models.UniqueConstraint(fields=('story', 'tone'), name='unique_story_tone'),
        ),
        migrations.AddConstraint(
            model_name='tellingbeat',
            constraint=models.UniqueConstraint(fields=('telling', 'order'), name='unique_beat_order'),
        ),
        migrations.AddConstraint(
            model_name='tellingproverb',
            constraint=models.UniqueConstraint(fields=('telling', 'slot'), name='unique_telling_slot'),
        ),
    ]
