# Generated by Django 5.2.17 on 2026-09-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storytelling',
            name='voice_style',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
