# Generated by Django 5.2.17 on 2026-10-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_storytelling_voice_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
