# Generated by Django 5.2.17 on 2026-09-24 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecallItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.PositiveSmallIntegerField(default=1)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('last_result', models.CharField(blank=True, max_length=32)),
                ('streak', models.PositiveSmallIntegerField(default=0)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recall_items', to='stories.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recall_items', to='memory.enduser')),
            ],
        ),
        migrations.CreateModel(
            name='StoryUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('articles', models.ManyToManyField(related_name='story_updates', to='news.article')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='stories.story')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to='stories.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to='memory.enduser')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'story'), name='unique_user_story_follow')],
            },
        ),
        migrations.CreateModel(
            name='StoryEncounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tone_heard', models.CharField(blank=True, max_length=10)),
                ('last_beat', models.PositiveSmallIntegerField(default=0)),
                ('tale_completed', models.BooleanField(default=False)),
                ('heard_at', models.DateTimeField(auto_now=True)),
                ('saved', models.BooleanField(default=False)),
                ('layers_explored', models.JSONField(blank=True, default=list)),
                ('last_layer', models.CharField(blank=True, max_length=20)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='stories.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='memory.enduser')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'story'), name='unique_user_story_encounter')],
            },
        ),
    ]
